front:
    image: nginx
    ports:
        - "11080:80"
    links:
        - "engine:engine"
    volumes:
        - ".:/workspace:rw"
        - "./docker/front/default.conf:/etc/nginx/conf.d/default.conf:ro"
engine:
    build: ./docker/engine/
    volumes:
        - ".:/workspace:rw"
        - "./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
    working_dir: "/workspace"
elk:
    image: willdurand/elk
    ports:
        - "11081:80"
    volumes:
        - ./docker/elk/logstash:/etc/logstash
        - ./docker/elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
        - front
        - engine