front:
    image: nginx
    ports:
        - "11080:80"
    links:
        - "engine:engine"
    volumes:
        - ".:/workspace:rw"
        - "./docker/front/default.conf:/etc/nginx/conf.d/default.conf:ro"

engine:
    build: ./docker/engine/
    volumes:
        - ".:/workspace:rw"
        - "./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
#    links:
#        - "db:db"
    working_dir: "/workspace"
elk:
    image: willdurand/elk
    ports:
        - 81:80
    volumes:
        - ./docker/elk/logstash:/etc/logstash
        - ./docker/elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
        - front
        - engine

#db:
#    image: mysql:5.7
#    ports:
#        - "3306:3306"
#    environment:
#        - "MYSQL_ROOT_PASSWORD=your_root_password"
#        - "MYSQL_USER=your_user"
#        - "MYSQL_PASSWORD=your_user_password"
#        - "MYSQL_DATABASE=your_database_name"